# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  skip_docs
  cocoapods(repo_update:true)
  
  private_lane :pgy do
    pgyer(api_key: "TODO")
  end

  desc "TEST版本 打包上传蒲公英"
  lane :test do
    match(
      type: "adhoc",
      readonly: is_ci
    )
    build_ios_app(
      scheme: "ProjectNameTest",
      clean: true,
    )
  
    pgy
  end

  desc "DEMO版本 打包上传蒲公英"
  lane :demo do
    match(
      type: "adhoc",
      readonly: is_ci
    )
    build_ios_app(
      scheme: "ProjectNameDemo",
      clean: true,
    )
  
    pgy
  end

  desc "正式版本 打包上传蒲公英"
  lane :prod do
    match(
      type: "appstore",
      readonly: is_ci
    )
    build_ios_app(
      scheme: "ProjectNameProduction",
      clean: true,
    )
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
    )
    pgy
  end

  desc "版本号和编译号修改"
  lane :ver do |options|
    increment_version_number(
      version_number: options[:ver], 
    )
    increment_build_number(
      build_number: options[:num],
    )
    # git_commit(path: ["./ProjectName/Info.plist", "./ProjectName.xcodeproj/project.pbxproj"], message: "fix: version & number upload done")
    # push_to_git_remote
  end
end
