# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  skip_docs

  private_lane :pgy do
    pgyer(api_key: "TODO")
  end
  
  desc "TEST版本 打包上传蒲公英"
  lane :test do
    gradle(task:'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      flavor: 'Qa',
      system_properties: {
        "ENVFILE": ".env.test"
      },
    )
    pgy
  end

  desc "DEMO版本 打包上传蒲公英"
  lane :demo do
    gradle(task:'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      flavor: 'Demo',
      system_properties: {
        "ENVFILE": ".env.demo"
      },
    )
    pgy
  end

  desc "正式版本 打包上传蒲公英"
  lane :prod do
    gradle(task:'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      flavor: 'Production',
      system_properties: {
        "ENVFILE": ".env.production"
      },
    )
    pgy
  end

  desc "版本号和编译号修改"
  lane :ver do |options|
    android_set_version_name(
      version_name: options[:ver],
    )
    android_set_version_code(
      version_code: options[:num], 
    )
    # git_commit(path: ["./app/build.gradle"], message: "fix: version & number upload done")
    # push_to_git_remote
  end

  after_all do |lane|
    if lane == :ver
      puts("version_name、version_code 修改完毕")
    else
      fastlane_directory = Dir.pwd
      apk_file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
      apk_path = fastlane_directory + "/outputs/com.projectname.apk"
      sh("mkdir", "-p", fastlane_directory +"/outputs")
      sh("cp", "-p", "-f", apk_file_path, apk_path)
      puts("apk保存路径： " + apk_path)
    end
  end
end
